# -----------------------------------------------------------------------------
# Site Settings
# -----------------------------------------------------------------------------

name: YOU Yufa
title: YOU Yufa
email: iyouyufa@gmail.com
description: Motion Planning, Self-Driving
url: youyufa.github.io

# -----------------------------------------------------------------------------
# Social Integration
# -----------------------------------------------------------------------------
scholar_userid: EFVk-mwAAAAJ
github_username: Youyufa
linkedin_username: yufa-you-2491a7228
contact_note: Feel free to drop me a line via email.

google_analytics: UA-54519238-1

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------

collections:
  news:
    defaults:
      layout: page
    output: true
    permalink: /news/:path/
  projects:
    output: false
    permalink: /projects/:path/

news_limit: 10

# -----------------------------------------------------------------------------
# Jekyll Settings
# -----------------------------------------------------------------------------

markdown: kramdown
include: ['_pages']
exclude: [node_modules, vendor, .bundle]

# Plugins
plugins:
  - jekyll-paginate
  - jekyll/scholar
  - jemoji

# Jekyll-Scholar
scholar:
  last_name: You
  style: apa
  locale: en
  sort_by: year
  order: descending
  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: publication
