# -----------------------------------------------------------------------------
# Site Settings
# -----------------------------------------------------------------------------

name: You Yufa
email: iyouyufa@gmail.com
description: Motion Planning, Self-Driving
# footer_text: >
#   Powered by <a href="http://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.
#   Hosted by <a href="https://pages.github.com/" target="_blank">GitHub Pages</a>.
# last_updated: true

url: youyufa.github.io

# -----------------------------------------------------------------------------
# Social Integration
# -----------------------------------------------------------------------------
scholar_userid: EFVk-mwAAAAJ
github_username: Youyufa
linkedin_username: yufa-you-2491a7228
facebook_username: yufa-you-2491a7228
twitter_username: yufa-you-2491a7228
contact_note: Feel free to drop me a line via email.

google_analytics: UA-54519238-1

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------

collections:
  news:
    defaults:
      layout: page
    output: true
    permalink: /news/:path/
  projects:
    output: false
    permalink: /projects/:path/

news_limit: 10

# -----------------------------------------------------------------------------
# Jekyll Settings
# -----------------------------------------------------------------------------

# Build settings
markdown: kramdown
# highlighter: pygments

# Include/Exclude
include: ['_pages']
exclude: [node_modules]

# Plugins
plugins:
  - jekyll-paginate
  - jekyll/scholar
  - jemoji

# Jekyll-Scholar
scholar:
  last_name: You
  style: apa
  locale: en
  sort_by: year
  order: descending
  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: publication
  reference_tagname: div

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

# -----------------------------------------------------------------------------
# Other settings
# -----------------------------------------------------------------------------

jquery_version: "1.12.4"
katex_version: "0.7.1"
anchorjs_version: "3.2.2"
